name: deploy

on:
  push:
    branches:    
      - deploy

jobs:
  build:

    runs-on: windows-2019
    
    steps:
      #Setup the environment
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: dotnet build --configuration Release
        
    - name: pack & publish
      run: |
        dotnet pack src\DenonLib\DenonLib.csproj --configuration Release
        dotnet nuget push src\DenonLib\bin\Release\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_PUBLISH}} --no-symbols true
		
		
	
